### ISSUE TITLE
Trailing new line results in 'org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. '

### ISSUE THREAD

**Issue by pawelprazak** [jOOQ/jOOX#128]
Simple test:

```
import org.joox.Match;
import org.junit.Test;

import static org.joox.JOOX.$;

public class TestJOOX {

    @Test
    public void testName() throws Exception {
        // given
        String xml = "<test/>\n";

        // when
        Match match = $(xml);
    }
}
```

Results in Xerxes Exception:

```
org.w3c.dom.DOMException: HIERARCHY_REQUEST_ERR: An attempt was made to insert a node where it is not permitted. 
at org.apache.xerces.dom.ParentNode.internalInsertBefore(Unknown Source)
at org.apache.xerces.dom.ParentNode.insertBefore(Unknown Source)
at org.apache.xerces.dom.CoreDocumentImpl.insertBefore(Unknown Source)
at org.apache.xerces.dom.NodeImpl.appendChild(Unknown Source)
at org.joox.JOOX.$(JOOX.java:117)
```

Looks like the new line '\n' is treated as a node:
![screenshot from 2014-10-06 14 31 43](https://cloud.githubusercontent.com/assets/48874/4525650/21226550-4d56-11e4-9b54-90d49eb401f6.png)

**Comment by pawelprazak** [comment]
When this will be released to maven?

**Comment by lukaseder** [comment]
I guess we can cut a release. It'll be on Maven Central within 1-2 hrs

**Comment by pawelprazak** [comment]
Many thanks :)

Pozdrawiam,
Paweł Prażak
--
+48 664 081 460
pawel.prazak@gmail.com

**Comment by lukaseder** [comment]
A more general case of this is:

- https://github.com/jOOQ/jOOX/issues/190
